### ISSUE TITLE
Waigo v2 roadmap

### ISSUE THREAD

**Issue by hiddentao** [waigo/waigo#28]
General:

* [x] Robust model layer.
* [x] Auto-invoke v8 harmony flag, so that `#!/usr/bin/env node` can be used on linux
* [x] Roles
* [x] Clustering - http://nodejs.org/api/cluster.html
* [x] ReactJS-powered admin pages
* [x] Route/API explorer - built-in interface for exploring all routes
* [x] ACL that can be applied to any type of action or resource. Loaded at startup.
* [x] Data editing interface - create, update, delete - and query filtering and paging
* [x] Reactive data - initially applicable to ACL (oplog tailing)
* [x] Extendable admin interface 
* [x] Replace ACE editor with something more lightweight
* [x] Emailing system
* [x] Forgot password system
* [x] Email user once signed up with confirmation link
* [x] Cron tasks

Pending specifics:

* [x] Ensure email addresses are unique to each user
* [x] XSRF-prevention for all forms
