### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by hiddentao** [waigo/waigo#42]
Currently working on this in the [rethink](https://github.com/waigo/waigo/tree/rethink) branch.

* [x] RethinkDB connections and models
* [x] Get user login pages working with RethinkDB
* [x] Modular model layer (to allow for both Mongo and RethinkDB to co-exist together)
* [x] Make RethinkDB the default
* [x] Remove thinky dependency and use rethinkdbdash on its own. Ensure can launch multiple workers with this model.
* [x] Remove alert msg feature (too confusing for users)
* [x] Split admin interface into a plugin
* [x] Cleanup all temporary files (e.g. for static file/folder copy)
* [x] Online docs site (guide)

Post-release work..

* [x] Refactor and rewrite model layer and re-add support for MongoDB (this is a big job as it will require updating [Robe](https://github.com/hiddentao/robe)). Perhaps a new NPM package is needed.

**Comment by hiddentao** [comment]
Done.
